#CC	= g++
#CPP	= g++
#CFLAG	= -DXP_UNIX -g -DDZHP 
#LIBPATH	= ../lib/
#BINPATH	= ../bin/
#INCLUDEPATH = -I../../include/ -I./  -I../  -I./include  -I../network/
#XLIB	= -lGL -lglut
#OBJECTS = JSDocument.o
#.PHONY: 3DIE
#3DIE:${OBJECTS}  
#%.o:%.c
#	${CC}  ${CFLAG}  ${INCLUDEPATH} -c $<
#%.o:%.cpp
#	${CPP}  ${CFLAG}  ${INCLUDEPATH} -c $<
#clean:
#	rm -f *.o 

TOPDIR= ../../
include ../../include/makefile.inc 
JSDocument.o:
include ../../include/rules.mk
