all:
	cd network;make
	cd js;make
	cd io;make
	cd multimedia;make
	cd fltkDisplay; make
clean:
	cd network;make clean
	cd js;make clean
	cd io;make clean
	cd multimedia;make clean
	cd htmlparser; make clean
	cd fltkDisplay; make clean


