all:dbg
dbg:
#	cd htmlparser; make dbg
#	cd js;make dbg 
#	cd io;make dbg 
#	cd network;make dbg 
#	cd multimedia;make dbg 
	cd glutDisplay; make dbg 
opt:
#	cd htmlparser; make opt 
#	cd js;make opt 
#	cd io;make  opt 
#	cd network;make  opt 
#	cd multimedia;make  opt 
	cd glutDisplay; make  opt 
clean:
	cd network;make clean
	cd js;make clean
	cd io;make clean
	cd multimedia;make clean
	cd htmlparser; make clean
	cd fltkDisplay; make clean
	cd glutDisplay; make clean


