TOPDIR= ../..
PROJ=display
EXEC	=

SRCS= Widget.cpp Group.cpp ctrinput.cpp Rect.cpp ctrbutton.cpp page.cpp #Cube.cpp display.cpp displayDraw.cpp 3DIE.c  
LIB_TARGET=libDisplay
#TARGET= libDisplay.a 
include ../../include/makefile.inc 

.phony:
#libDisplay.a: ${OBJS}
#	ar ${ARFLAG} ${LIBPATH}/$@ $^
include ../../include/rules.mk

